[book]
title = "Personal Ledger Documentation"
authors = ["Ian Teda"]
description = "Documentation for the Personal Ledger."
src = "docs/src"
language = "en"
text-direction = "ltr"

[rust]
edition = "2021"  # Github Pages currently requires 2021 edition for mdBook

[build]
build-dir = "docs/.book/"
create-missing = false
extra-watch-dirs = ["docs/src"] 


[output.html]
default-theme = "dark"
# additional-css = ["custom.css"]

[output.html.search]
limit-results = 30

[preprocessor.index]

[preprocessor.links]

