[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]

lib_rpc = { path = "../../crates/libs/lib-rpc" }


tokio = { workspace = true }
tonic = { workspace = true }


[lints]
workspace = true
