[tasks.backend-run]
description = "Run the backend binary"
command = "cargo"
args = ["run", "--bin", "backend"]


[tasks.backend-build]
description = "Build the backend binary"
command = "cargo"
args = ["build", "--package", "backend", "--bin", "backend", "--release"]
